### ISSUE TITLE
Does TIF work well for non-LTRs ?

### ISSUE THREAD

**Issue by HounerX** [akiomiyao/tif#1]
Hello, 
         I have been trying to use TIF for a non-LTR in drosophila. I am having hard time deciding how many bp i should include in the 5' and 3' ? Also it is important to note that the 3' has a poly(A) should i include that ?

I tried multiple stuff and no luck with getting an output. Do you have any advice please ?

Thank you so much

**Comment by akiomiyao** [comment]
Hi,
Currently, TIF is not supported for non-LTR retrotransposons. If you know accession numbers of NGS containing sequences of jumped non-LTR retrotransposons, let me know accession numbers. I will add scripts for non-LTR retrotransposons.
Thank you for your comment,
Akio

**Comment by HounerX** [comment]
Thank you so much for responding. 

Here are the accession numbers. They should all have insertions of non-LTRs.
[DGRP.names.list.txt](https://github.com/akiomiyao/tif/files/5085114/DGRP.names.list.txt)

The non-LTR we are interested in is Jockey-3. Here is the consensus sequence if that would help

[jockey-3_DM_Consensus_06052020.txt](https://github.com/akiomiyao/tif/files/5085140/jockey-3_DM_Consensus_06052020.txt)


Thank you so much.

**Comment by akiomiyao** [comment]
Hi,

Initial version of  tif_nonltr.pl is now registered.

Usage is 
perl tif_nonltr.pl SRR834538 dmel626.fasta GAACCCTCTGTCGTAGAACACTACTA

I attempted to detect the transposition from some accessions of your list.
But I can not detect transposition. If you know accession with transposition of jockey-3, try the accession first.

Akio

**Comment by HounerX** [comment]
Hello thank you so much. I have reran the program on accession numbers and I got output written in the result. like that for example 
![image](https://user-images.githubusercontent.com/25706324/90644430-b607d500-e202-11ea-8095-bb69bce1d4bd.png)

Does this indicate the insertion site in the reference genome ? what is the difference between labaling head and tail ? 

I did check at the coordinates within a window and it looks similar to TSD we see 


Thank you so much

**Comment by akiomiyao** [comment]
Hi,

Because downstream flanking sequence of non-LTR-retrotransposons may have unclear TSD, tif_nonltr.pl detect junction within 100bp distance between junctions of head and polyA tail of the retrotransposon. The transposon may be inserted in the Y_Contig26.

Akio

**Comment by HounerX** [comment]
oh thank you so much for all the help, so can i interpret that between these coordinates a might be a possible target insertion ?

**Comment by akiomiyao** [comment]
Yes, may be.

If fragment is obtained by PCR with primers between the target region and the transposon, the transposon should be inserted at the target region.

Akio

**Comment by HounerX** [comment]
Thank you so much for all the help. I really appreciate it. This helped us.
